FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./app ./

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /tgconn-app

FROM scratch

WORKDIR /app

COPY --from=builder /tgconn-app .

EXPOSE 5555

CMD [ "/app/tgconn-app" ]
